{"uuid": "026a1d64-6687-4c48-b3a8-0a1dc30f6f6b", "children": ["3f839a92-ee5e-4215-8a7e-e13f9d261406", "dcab8594-47cf-4e85-9807-f1151a2acb9a"], "befores": [{"name": "test_setup", "status": "passed", "start": 1674639553408, "stop": 1674639563820}], "afters": [{"name": "test_setup::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: disconnected: unable to connect to renderer\n  (failed to check if window was closed: disconnected: unable to connect to renderer)\n  (Session info: chrome=108.0.5359.125)\nStacktrace:\nBacktrace:\n\t(No symbol) [0x00F2F243]\n\t(No symbol) [0x00EB7FD1]\n\t(No symbol) [0x00DAD04D]\n\t(No symbol) [0x00D9D3F8]\n\t(No symbol) [0x00D914E4]\n\t(No symbol) [0x00D92344]\n\t(No symbol) [0x00E017A5]\n\t(No symbol) [0x00DF8553]\n\t(No symbol) [0x00DD163C]\n\t(No symbol) [0x00DD269D]\n\tGetHandleVerifier [0x011C9A22+2655074]\n\tGetHandleVerifier [0x011BCA24+2601828]\n\tGetHandleVerifier [0x00FD8C0A+619850]\n\tGetHandleVerifier [0x00FD7830+614768]\n\t(No symbol) [0x00EC05FC]\n\t(No symbol) [0x00EC5968]\n\t(No symbol) [0x00EC5A55]\n\t(No symbol) [0x00ED051B]\n\tBaseThreadInitThunk [0x75530619+25]\n\tRtlGetAppContainerNamedObjectPath [0x7758784D+237]\n\tRtlGetAppContainerNamedObjectPath [0x7758781D+189]\n\n", "trace": "  File \"D:\\Users\\pvelu\\Documents\\ACM\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Users\\pvelu\\Documents\\ACM\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 941, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\Users\\pvelu\\Documents\\UI_Automation\\TestCases\\conftest.py\", line 79, in test_setup\n    driver.close()\n  File \"D:\\Users\\pvelu\\Documents\\ACM\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 552, in close\n    self.execute(Command.CLOSE)\n  File \"D:\\Users\\pvelu\\Documents\\ACM\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Users\\pvelu\\Documents\\ACM\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1674639605676, "stop": 1674639613793}], "start": 1674639553408, "stop": 1674639613793}